version: '3.7'
services:
  qemu:
    image: andrerichter/raspi3-utils
    env_file:
      - .env
    networks:
         qemu_network:
           ipv4_address: 172.20.0.2
    ports:
      - "5900:5900"
    volumes:
      - ".:/work"
    working_dir: /work
    command: qemu-system-aarch64 -M raspi3 -drive format=raw,file=${KERNEL_FILE} -d in_asm -vnc :0
networks:
  qemu_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
