version: '3.7'
services:
  rasp:
    image: andrerichter/raspi3-utils
    env_file:
      - .env
    networks:
         qemu_network:
           ipv4_address: 172.20.0.2
    ports:
      - "5900:5900"
    volumes:
      - ".:/work"
    working_dir: /work
    command: qemu-system-aarch64 -M raspi3 -drive format=raw,file=${RUSTYPI} -vnc :0 -d in_asm

  x86_64:
    image:  maxtnt/qemu-tester
    env_file:
      - .env
    networks:
         qemu_network:
           ipv4_address: 172.20.0.3
    ports:
      - "5900:5900"
    volumes:
      - ".:/work"
    working_dir: /work
    command: qemu-system-x86_64 -drive format=raw,file=${X86_64} -vnc :0 -d in_asm
networks:
  qemu_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
